### ISSUE TITLE
--enable-kernel-linux option does not work

### ISSUE THREAD

**Issue by jfigus** [cisco/libsrtp#81]
When using the --enable-kernel-linux option, the following error results:

gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops -c srtp/srtp.c -o srtp/srtp.o
In file included from crypto/include/integers.h:53:0,
                 from crypto/include/datatypes.h:50,
                 from crypto/include/rdbx.h:14,
                 from ./include/srtp_priv.h:50,
                 from srtp/srtp.c:46:
crypto/include/kernel_compat.h:52:24: fatal error: linux/slab.h: No such file or directory
 #include <linux/slab.h>
                        ^
compilation terminated.
make: **\* [srtp/srtp.o] Error 1

Does anyone have concerns over removing this option from the configure script?

**Comment by s1885** [comment]
I was using ver 1.4.4 and compiled as a kernel module. Now I would like to upgrade to 2.0.0 or 2.1.0, But I see that --enable-kernel-linux support is removed. Is there any idea to bring this back?

**Comment by paulej** [comment]
I think any reasonable contribution to the code would be welcome.  I would caution against doing it right away, as the build scripts are undergoing substantial change.  However, we're looking for a 2.1 release soon.  If that functionality is important, then perhaps submit a PR and we can review it.

**Comment by ealfan** [comment]
We also use this option in our code. 1.5.4 supports this option. If 2.x begin to support --enable-kernel-linux option, we can upgrade to that release, otherwise we are stuck in 1.5.4 release.

**Comment by achehab1** [comment]
Hi @ealfan, can you please put you configuration command line ?
we cannot enable and compile using thios option using 1.5.4 version
thank you !
