### ISSUE TITLE
how can I build a version 1.6 with openssl 1.1.0 ?

### ISSUE THREAD

**Issue by themaddoctor** [cisco/libsrtp#394]
```
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops  -c srtp/srtp.c -o srtp/srtp.o
In file included from crypto/include/prng.h:53:0,
                 from crypto/include/crypto_kernel.h:50,
                 from ./include/srtp_priv.h:58,
                 from srtp/srtp.c:46:
crypto/include/aes_icm_ossl.h:75:20: error: field ‘ctx’ has incomplete type
     EVP_CIPHER_CTX ctx;
                    ^~~
In file included from srtp/srtp.c:50:0:
crypto/include/aes_gcm_ossl.h:58:18: error: field ‘ctx’ has incomplete type
   EVP_CIPHER_CTX ctx;
                  ^~~
make: *** [Makefile:110: srtp/srtp.o] Error 1
```

**Comment by JonathanLennox** [comment]
LibSRTP 2.1.0 can build with OpenSSL 1.1.0 (since commit 0b45423); however, this change was made after the branch to 1.6.

You can either upgrade to 2.1.0 (this will require some code changes in the callers, but not major ones), or build LibSRTP 1.6 without OpenSSL (using only its built-in crypto).

Alternately, you might be able to back-merge 0b45423 without too much difficulty.

**Comment by paulej** [comment]
A quick Google search suggests this might be due to an OpenSSL API change.  I'm not sure what changed and why.

It will require some change in libsrtp, unless OpenSSL will be making changes to fix this.  Rather unfortunate to make API changes that break lots of other projects.

Paul


-------- Original Message --------

**Comment by themaddoctor** [comment]
It was fixed in libsrtp version 2.1, so why not in 1.6 ?

[I am aware of the reason that it breaks. Some things are no longer
visible in the API]


On 1/19/18, Paul E. Jones <notifications@github.com> wrote:
> A quick Google search suggests this might be due to an OpenSSL API change.
> I'm not sure what changed and why.
>
> It will require some change in libsrtp, unless OpenSSL will be making
> changes to fix this.  Rather unfortunate to make API changes that break lots
> of other projects.
>
> Paul
>
>
> -------- Original Message --------
> From: themaddoctor <notifications@github.com>
> Sent: January 19, 2018 4:35:09 AM EST
> To: cisco/libsrtp <libsrtp@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [cisco/libsrtp] how can I build a version 1.6 with openssl 1.1.0 ?
> (#394)
>
> ```
> gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC
> -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops  -c srtp/srtp.c -o
> srtp/srtp.o
> In file included from crypto/include/prng.h:53:0,
>                  from crypto/include/crypto_kernel.h:50,
>                  from ./include/srtp_priv.h:58,
>                  from srtp/srtp.c:46:
> crypto/include/aes_icm_ossl.h:75:20: error: field ‘ctx’ has incomplete type
>      EVP_CIPHER_CTX ctx;
>                     ^~~
> In file included from srtp/srtp.c:50:0:
> crypto/include/aes_gcm_ossl.h:58:18: error: field ‘ctx’ has incomplete type
>    EVP_CIPHER_CTX ctx;
>                   ^~~
> make: *** [Makefile:110: srtp/srtp.o] Error 1
> ```
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cisco/libsrtp/issues/394
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cisco/libsrtp/issues/394#issuecomment-359013076


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by themaddoctor** [comment]
qtwebengine 5.10.0 wants libsrtp 1 it seems.

**Comment by themaddoctor** [comment]
@JonathanLennox I saw that change a while ago while I was searching. Is there a link to a usable patch? There are over 100 lines that are changed, and I am not good enough at github to be able to turn what I see into a patch easily. (Where the patch uses fuzz or fails, I can figure out how to fix it)

**Comment by pabuhler** [comment]
Closing this issues as it is over a year old and there are no plans for changes. If you still have issues them please reopen and we can try to find a solution.
